#!/bin/bash

# Help script - shows available commands and tips

echo "📚 Coding Help - Available Commands"
echo "===================================="
echo ""
echo "🐍 Python Commands:"
echo "  python3 mahesh.py           - Run your Python script"
echo "  python3 your_file.py        - Run any Python file"
echo ""
echo "🛠️  Helper Scripts:"
echo "  bash run.sh                 - Run mahesh.py (or: bash run.sh file.py)"
echo "  bash run_college_site.sh    - Start Mahesh College Counseling site (http://localhost:3000)"
echo "  bash check_setup.sh         - Check if everything is set up correctly"
echo "  bash test_python.sh         - Test if Python works"
echo "  bash create_project.sh name - Create a new Python file"
echo "  bash help.sh                - Show this help message"
echo ""
echo "📖 Documentation:"
echo "  README.md                   - Main guide"
echo "  SETUP_GUIDE.md              - Detailed setup instructions"
echo "  QUICK_START.md              - Quick start guide"
echo ""
echo "💡 Tips:"
echo "  - Write code in Cursor (your editor)"
echo "  - Run code in Terminal"
echo "  - Ask Claude in Cursor for help with coding"
echo "  - Python files end with .py"
echo ""
echo "🎯 Common Tasks:"
echo "  1. Create new file:     bash create_project.sh my_script"
echo "  2. Run your file:       bash run.sh my_script.py"
echo "  3. Check setup:         bash check_setup.sh"
echo ""

